policy:
  - template: [bug_report.yml]
    section:
      - id: [minecraftVersion]
        label:
          - name: 1.21.1
            keys: [1.21.1]
          - name: 1.20.1
            keys: [1.20.1]

      - id: [modLoader]
        label:
          - name: neoforge
            keys: [NeoForge]
          - name: forge
            keys: [Forge]
          - name: fabric
            keys: [Fabric]
