# Publishing
release_type=beta
curseforge_project_id=1255994
# curseforge_token=
modrinth_project_id=i9ljQ5sI
# modrinth_token=

# Mod
mod_id=buildersvoid
mod_group=dev.detpikachu
mod_version=21.1.0-beta2
mod_name=Builder's Void
mod_license=GNU GPLv3
mod_author=zach473, detpikachu
mod_credits=
mod_description=A void dimension for all your building needs!
mod_source=https://github.com/devpikachu/builders-void
mod_issues=https://github.com/devpikachu/builders-void/issues

# Minecraft
java_version=21
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
parchment_version=2024.11.17
neoform_version=20240808.144430

# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.17.3

# Forge
neoforge_version=21.1.213
neoforge_loader_version_range=[4,)

# Dependencies
balm_version=21.0.53
cloth_config_version=15.0.140

# Dev dependencies
jei_version=19.25.0.323
modmenu_version=11.0.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
